// Code generated by go-swagger; DO NOT EDIT.

package exec_compat

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCreateExecParams creates a new CreateExecParams object
// with the default values initialized.
func NewCreateExecParams() *CreateExecParams {
	var ()
	return &CreateExecParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateExecParamsWithTimeout creates a new CreateExecParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateExecParamsWithTimeout(timeout time.Duration) *CreateExecParams {
	var ()
	return &CreateExecParams{

		timeout: timeout,
	}
}

// NewCreateExecParamsWithContext creates a new CreateExecParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateExecParamsWithContext(ctx context.Context) *CreateExecParams {
	var ()
	return &CreateExecParams{

		Context: ctx,
	}
}

// NewCreateExecParamsWithHTTPClient creates a new CreateExecParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateExecParamsWithHTTPClient(client *http.Client) *CreateExecParams {
	var ()
	return &CreateExecParams{
		HTTPClient: client,
	}
}

/*CreateExecParams contains all the parameters to send to the API endpoint
for the create exec operation typically these are written to a http.Request
*/
type CreateExecParams struct {

	/*Control
	  Attributes for create

	*/
	Control CreateExecBody
	/*Name
	  name of container

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create exec params
func (o *CreateExecParams) WithTimeout(timeout time.Duration) *CreateExecParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create exec params
func (o *CreateExecParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create exec params
func (o *CreateExecParams) WithContext(ctx context.Context) *CreateExecParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create exec params
func (o *CreateExecParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create exec params
func (o *CreateExecParams) WithHTTPClient(client *http.Client) *CreateExecParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create exec params
func (o *CreateExecParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithControl adds the control to the create exec params
func (o *CreateExecParams) WithControl(control CreateExecBody) *CreateExecParams {
	o.SetControl(control)
	return o
}

// SetControl adds the control to the create exec params
func (o *CreateExecParams) SetControl(control CreateExecBody) {
	o.Control = control
}

// WithName adds the name to the create exec params
func (o *CreateExecParams) WithName(name string) *CreateExecParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the create exec params
func (o *CreateExecParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *CreateExecParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Control); err != nil {
		return err
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
