// Code generated by go-swagger; DO NOT EDIT.

package exec_compat

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ResizeExecReader is a Reader for the ResizeExec structure.
type ResizeExecReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ResizeExecReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewResizeExecCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewResizeExecNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewResizeExecInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewResizeExecCreated creates a ResizeExecCreated with default headers values
func NewResizeExecCreated() *ResizeExecCreated {
	return &ResizeExecCreated{}
}

/*ResizeExecCreated handles this case with default header values.

no error
*/
type ResizeExecCreated struct {
}

func (o *ResizeExecCreated) Error() string {
	return fmt.Sprintf("[POST /exec/{id}/resize][%d] resizeExecCreated ", 201)
}

func (o *ResizeExecCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewResizeExecNotFound creates a ResizeExecNotFound with default headers values
func NewResizeExecNotFound() *ResizeExecNotFound {
	return &ResizeExecNotFound{}
}

/*ResizeExecNotFound handles this case with default header values.

No such exec instance
*/
type ResizeExecNotFound struct {
	Payload *ResizeExecNotFoundBody
}

func (o *ResizeExecNotFound) Error() string {
	return fmt.Sprintf("[POST /exec/{id}/resize][%d] resizeExecNotFound  %+v", 404, o.Payload)
}

func (o *ResizeExecNotFound) GetPayload() *ResizeExecNotFoundBody {
	return o.Payload
}

func (o *ResizeExecNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ResizeExecNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewResizeExecInternalServerError creates a ResizeExecInternalServerError with default headers values
func NewResizeExecInternalServerError() *ResizeExecInternalServerError {
	return &ResizeExecInternalServerError{}
}

/*ResizeExecInternalServerError handles this case with default header values.

Internal server error
*/
type ResizeExecInternalServerError struct {
	Payload *ResizeExecInternalServerErrorBody
}

func (o *ResizeExecInternalServerError) Error() string {
	return fmt.Sprintf("[POST /exec/{id}/resize][%d] resizeExecInternalServerError  %+v", 500, o.Payload)
}

func (o *ResizeExecInternalServerError) GetPayload() *ResizeExecInternalServerErrorBody {
	return o.Payload
}

func (o *ResizeExecInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ResizeExecInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*ResizeExecInternalServerErrorBody resize exec internal server error body
swagger:model ResizeExecInternalServerErrorBody
*/
type ResizeExecInternalServerErrorBody struct {

	// API root cause formatted for automated parsing
	Because string `json:"cause,omitempty"`

	// human error message, formatted for a human to read
	Message string `json:"message,omitempty"`

	// http response code
	ResponseCode int64 `json:"response,omitempty"`
}

// Validate validates this resize exec internal server error body
func (o *ResizeExecInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ResizeExecInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ResizeExecInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res ResizeExecInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*ResizeExecNotFoundBody resize exec not found body
swagger:model ResizeExecNotFoundBody
*/
type ResizeExecNotFoundBody struct {

	// API root cause formatted for automated parsing
	Because string `json:"cause,omitempty"`

	// human error message, formatted for a human to read
	Message string `json:"message,omitempty"`

	// http response code
	ResponseCode int64 `json:"response,omitempty"`
}

// Validate validates this resize exec not found body
func (o *ResizeExecNotFoundBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ResizeExecNotFoundBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ResizeExecNotFoundBody) UnmarshalBinary(b []byte) error {
	var res ResizeExecNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
