// Code generated by go-swagger; DO NOT EDIT.

package containers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewLibpodResizeContainerParams creates a new LibpodResizeContainerParams object
// with the default values initialized.
func NewLibpodResizeContainerParams() *LibpodResizeContainerParams {
	var ()
	return &LibpodResizeContainerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewLibpodResizeContainerParamsWithTimeout creates a new LibpodResizeContainerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewLibpodResizeContainerParamsWithTimeout(timeout time.Duration) *LibpodResizeContainerParams {
	var ()
	return &LibpodResizeContainerParams{

		timeout: timeout,
	}
}

// NewLibpodResizeContainerParamsWithContext creates a new LibpodResizeContainerParams object
// with the default values initialized, and the ability to set a context for a request
func NewLibpodResizeContainerParamsWithContext(ctx context.Context) *LibpodResizeContainerParams {
	var ()
	return &LibpodResizeContainerParams{

		Context: ctx,
	}
}

// NewLibpodResizeContainerParamsWithHTTPClient creates a new LibpodResizeContainerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewLibpodResizeContainerParamsWithHTTPClient(client *http.Client) *LibpodResizeContainerParams {
	var ()
	return &LibpodResizeContainerParams{
		HTTPClient: client,
	}
}

/*LibpodResizeContainerParams contains all the parameters to send to the API endpoint
for the libpod resize container operation typically these are written to a http.Request
*/
type LibpodResizeContainerParams struct {

	/*H
	  Height to set for the terminal, in characters

	*/
	H *int64
	/*Name
	  the name or ID of the container

	*/
	Name string
	/*W
	  Width to set for the terminal, in characters

	*/
	W *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the libpod resize container params
func (o *LibpodResizeContainerParams) WithTimeout(timeout time.Duration) *LibpodResizeContainerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the libpod resize container params
func (o *LibpodResizeContainerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the libpod resize container params
func (o *LibpodResizeContainerParams) WithContext(ctx context.Context) *LibpodResizeContainerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the libpod resize container params
func (o *LibpodResizeContainerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the libpod resize container params
func (o *LibpodResizeContainerParams) WithHTTPClient(client *http.Client) *LibpodResizeContainerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the libpod resize container params
func (o *LibpodResizeContainerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithH adds the h to the libpod resize container params
func (o *LibpodResizeContainerParams) WithH(h *int64) *LibpodResizeContainerParams {
	o.SetH(h)
	return o
}

// SetH adds the h to the libpod resize container params
func (o *LibpodResizeContainerParams) SetH(h *int64) {
	o.H = h
}

// WithName adds the name to the libpod resize container params
func (o *LibpodResizeContainerParams) WithName(name string) *LibpodResizeContainerParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the libpod resize container params
func (o *LibpodResizeContainerParams) SetName(name string) {
	o.Name = name
}

// WithW adds the w to the libpod resize container params
func (o *LibpodResizeContainerParams) WithW(w *int64) *LibpodResizeContainerParams {
	o.SetW(w)
	return o
}

// SetW adds the w to the libpod resize container params
func (o *LibpodResizeContainerParams) SetW(w *int64) {
	o.W = w
}

// WriteToRequest writes these params to a swagger request
func (o *LibpodResizeContainerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.H != nil {

		// query param h
		var qrH int64
		if o.H != nil {
			qrH = *o.H
		}
		qH := swag.FormatInt64(qrH)
		if qH != "" {
			if err := r.SetQueryParam("h", qH); err != nil {
				return err
			}
		}

	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if o.W != nil {

		// query param w
		var qrW int64
		if o.W != nil {
			qrW = *o.W
		}
		qW := swag.FormatInt64(qrW)
		if qW != "" {
			if err := r.SetQueryParam("w", qW); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
