// Code generated by go-swagger; DO NOT EDIT.

package containers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewLibpodInitContainerParams creates a new LibpodInitContainerParams object
// with the default values initialized.
func NewLibpodInitContainerParams() *LibpodInitContainerParams {
	var ()
	return &LibpodInitContainerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewLibpodInitContainerParamsWithTimeout creates a new LibpodInitContainerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewLibpodInitContainerParamsWithTimeout(timeout time.Duration) *LibpodInitContainerParams {
	var ()
	return &LibpodInitContainerParams{

		timeout: timeout,
	}
}

// NewLibpodInitContainerParamsWithContext creates a new LibpodInitContainerParams object
// with the default values initialized, and the ability to set a context for a request
func NewLibpodInitContainerParamsWithContext(ctx context.Context) *LibpodInitContainerParams {
	var ()
	return &LibpodInitContainerParams{

		Context: ctx,
	}
}

// NewLibpodInitContainerParamsWithHTTPClient creates a new LibpodInitContainerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewLibpodInitContainerParamsWithHTTPClient(client *http.Client) *LibpodInitContainerParams {
	var ()
	return &LibpodInitContainerParams{
		HTTPClient: client,
	}
}

/*LibpodInitContainerParams contains all the parameters to send to the API endpoint
for the libpod init container operation typically these are written to a http.Request
*/
type LibpodInitContainerParams struct {

	/*Name
	  the name or ID of the container

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the libpod init container params
func (o *LibpodInitContainerParams) WithTimeout(timeout time.Duration) *LibpodInitContainerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the libpod init container params
func (o *LibpodInitContainerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the libpod init container params
func (o *LibpodInitContainerParams) WithContext(ctx context.Context) *LibpodInitContainerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the libpod init container params
func (o *LibpodInitContainerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the libpod init container params
func (o *LibpodInitContainerParams) WithHTTPClient(client *http.Client) *LibpodInitContainerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the libpod init container params
func (o *LibpodInitContainerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the libpod init container params
func (o *LibpodInitContainerParams) WithName(name string) *LibpodInitContainerParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the libpod init container params
func (o *LibpodInitContainerParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *LibpodInitContainerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
