// Code generated by go-swagger; DO NOT EDIT.

package containers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LibpodStartContainerReader is a Reader for the LibpodStartContainer structure.
type LibpodStartContainerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LibpodStartContainerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewLibpodStartContainerNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 304:
		result := NewLibpodStartContainerNotModified()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewLibpodStartContainerNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewLibpodStartContainerInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewLibpodStartContainerNoContent creates a LibpodStartContainerNoContent with default headers values
func NewLibpodStartContainerNoContent() *LibpodStartContainerNoContent {
	return &LibpodStartContainerNoContent{}
}

/*LibpodStartContainerNoContent handles this case with default header values.

no error
*/
type LibpodStartContainerNoContent struct {
}

func (o *LibpodStartContainerNoContent) Error() string {
	return fmt.Sprintf("[POST /libpod/containers/{name}/start][%d] libpodStartContainerNoContent ", 204)
}

func (o *LibpodStartContainerNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewLibpodStartContainerNotModified creates a LibpodStartContainerNotModified with default headers values
func NewLibpodStartContainerNotModified() *LibpodStartContainerNotModified {
	return &LibpodStartContainerNotModified{}
}

/*LibpodStartContainerNotModified handles this case with default header values.

Container already started
*/
type LibpodStartContainerNotModified struct {
	Payload *LibpodStartContainerNotModifiedBody
}

func (o *LibpodStartContainerNotModified) Error() string {
	return fmt.Sprintf("[POST /libpod/containers/{name}/start][%d] libpodStartContainerNotModified  %+v", 304, o.Payload)
}

func (o *LibpodStartContainerNotModified) GetPayload() *LibpodStartContainerNotModifiedBody {
	return o.Payload
}

func (o *LibpodStartContainerNotModified) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(LibpodStartContainerNotModifiedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLibpodStartContainerNotFound creates a LibpodStartContainerNotFound with default headers values
func NewLibpodStartContainerNotFound() *LibpodStartContainerNotFound {
	return &LibpodStartContainerNotFound{}
}

/*LibpodStartContainerNotFound handles this case with default header values.

No such container
*/
type LibpodStartContainerNotFound struct {
	Payload *LibpodStartContainerNotFoundBody
}

func (o *LibpodStartContainerNotFound) Error() string {
	return fmt.Sprintf("[POST /libpod/containers/{name}/start][%d] libpodStartContainerNotFound  %+v", 404, o.Payload)
}

func (o *LibpodStartContainerNotFound) GetPayload() *LibpodStartContainerNotFoundBody {
	return o.Payload
}

func (o *LibpodStartContainerNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(LibpodStartContainerNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLibpodStartContainerInternalServerError creates a LibpodStartContainerInternalServerError with default headers values
func NewLibpodStartContainerInternalServerError() *LibpodStartContainerInternalServerError {
	return &LibpodStartContainerInternalServerError{}
}

/*LibpodStartContainerInternalServerError handles this case with default header values.

Internal server error
*/
type LibpodStartContainerInternalServerError struct {
	Payload *LibpodStartContainerInternalServerErrorBody
}

func (o *LibpodStartContainerInternalServerError) Error() string {
	return fmt.Sprintf("[POST /libpod/containers/{name}/start][%d] libpodStartContainerInternalServerError  %+v", 500, o.Payload)
}

func (o *LibpodStartContainerInternalServerError) GetPayload() *LibpodStartContainerInternalServerErrorBody {
	return o.Payload
}

func (o *LibpodStartContainerInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(LibpodStartContainerInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*LibpodStartContainerInternalServerErrorBody libpod start container internal server error body
swagger:model LibpodStartContainerInternalServerErrorBody
*/
type LibpodStartContainerInternalServerErrorBody struct {

	// API root cause formatted for automated parsing
	Because string `json:"cause,omitempty"`

	// human error message, formatted for a human to read
	Message string `json:"message,omitempty"`

	// http response code
	ResponseCode int64 `json:"response,omitempty"`
}

// Validate validates this libpod start container internal server error body
func (o *LibpodStartContainerInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *LibpodStartContainerInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *LibpodStartContainerInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res LibpodStartContainerInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*LibpodStartContainerNotFoundBody libpod start container not found body
swagger:model LibpodStartContainerNotFoundBody
*/
type LibpodStartContainerNotFoundBody struct {

	// API root cause formatted for automated parsing
	Because string `json:"cause,omitempty"`

	// human error message, formatted for a human to read
	Message string `json:"message,omitempty"`

	// http response code
	ResponseCode int64 `json:"response,omitempty"`
}

// Validate validates this libpod start container not found body
func (o *LibpodStartContainerNotFoundBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *LibpodStartContainerNotFoundBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *LibpodStartContainerNotFoundBody) UnmarshalBinary(b []byte) error {
	var res LibpodStartContainerNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*LibpodStartContainerNotModifiedBody libpod start container not modified body
swagger:model LibpodStartContainerNotModifiedBody
*/
type LibpodStartContainerNotModifiedBody struct {

	// API root cause formatted for automated parsing
	Because string `json:"cause,omitempty"`

	// human error message, formatted for a human to read
	Message string `json:"message,omitempty"`

	// http response code
	ResponseCode int64 `json:"response,omitempty"`
}

// Validate validates this libpod start container not modified body
func (o *LibpodStartContainerNotModifiedBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *LibpodStartContainerNotModifiedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *LibpodStartContainerNotModifiedBody) UnmarshalBinary(b []byte) error {
	var res LibpodStartContainerNotModifiedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
