// Code generated by go-swagger; DO NOT EDIT.

package containers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewLibpodWaitContainerParams creates a new LibpodWaitContainerParams object
// with the default values initialized.
func NewLibpodWaitContainerParams() *LibpodWaitContainerParams {
	var ()
	return &LibpodWaitContainerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewLibpodWaitContainerParamsWithTimeout creates a new LibpodWaitContainerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewLibpodWaitContainerParamsWithTimeout(timeout time.Duration) *LibpodWaitContainerParams {
	var ()
	return &LibpodWaitContainerParams{

		timeout: timeout,
	}
}

// NewLibpodWaitContainerParamsWithContext creates a new LibpodWaitContainerParams object
// with the default values initialized, and the ability to set a context for a request
func NewLibpodWaitContainerParamsWithContext(ctx context.Context) *LibpodWaitContainerParams {
	var ()
	return &LibpodWaitContainerParams{

		Context: ctx,
	}
}

// NewLibpodWaitContainerParamsWithHTTPClient creates a new LibpodWaitContainerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewLibpodWaitContainerParamsWithHTTPClient(client *http.Client) *LibpodWaitContainerParams {
	var ()
	return &LibpodWaitContainerParams{
		HTTPClient: client,
	}
}

/*LibpodWaitContainerParams contains all the parameters to send to the API endpoint
for the libpod wait container operation typically these are written to a http.Request
*/
type LibpodWaitContainerParams struct {

	/*Condition
	  wait until container is to a given condition. default is stopped. valid conditions are:
	  - configured
	  - created
	  - exited
	  - paused
	  - running
	  - stopped


	*/
	Condition *string
	/*Name
	  the name or ID of the container

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the libpod wait container params
func (o *LibpodWaitContainerParams) WithTimeout(timeout time.Duration) *LibpodWaitContainerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the libpod wait container params
func (o *LibpodWaitContainerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the libpod wait container params
func (o *LibpodWaitContainerParams) WithContext(ctx context.Context) *LibpodWaitContainerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the libpod wait container params
func (o *LibpodWaitContainerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the libpod wait container params
func (o *LibpodWaitContainerParams) WithHTTPClient(client *http.Client) *LibpodWaitContainerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the libpod wait container params
func (o *LibpodWaitContainerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCondition adds the condition to the libpod wait container params
func (o *LibpodWaitContainerParams) WithCondition(condition *string) *LibpodWaitContainerParams {
	o.SetCondition(condition)
	return o
}

// SetCondition adds the condition to the libpod wait container params
func (o *LibpodWaitContainerParams) SetCondition(condition *string) {
	o.Condition = condition
}

// WithName adds the name to the libpod wait container params
func (o *LibpodWaitContainerParams) WithName(name string) *LibpodWaitContainerParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the libpod wait container params
func (o *LibpodWaitContainerParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *LibpodWaitContainerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Condition != nil {

		// query param condition
		var qrCondition string
		if o.Condition != nil {
			qrCondition = *o.Condition
		}
		qCondition := qrCondition
		if qCondition != "" {
			if err := r.SetQueryParam("condition", qCondition); err != nil {
				return err
			}
		}

	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
