# Copyright IBM Corp. 2019, 2026
# SPDX-License-Identifier: MPL-2.0

version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "theme/dependency"
