// Code generated by go-swagger; DO NOT EDIT.

package volumes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPruneVolumesParams creates a new PruneVolumesParams object
// with the default values initialized.
func NewPruneVolumesParams() *PruneVolumesParams {

	return &PruneVolumesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPruneVolumesParamsWithTimeout creates a new PruneVolumesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPruneVolumesParamsWithTimeout(timeout time.Duration) *PruneVolumesParams {

	return &PruneVolumesParams{

		timeout: timeout,
	}
}

// NewPruneVolumesParamsWithContext creates a new PruneVolumesParams object
// with the default values initialized, and the ability to set a context for a request
func NewPruneVolumesParamsWithContext(ctx context.Context) *PruneVolumesParams {

	return &PruneVolumesParams{

		Context: ctx,
	}
}

// NewPruneVolumesParamsWithHTTPClient creates a new PruneVolumesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPruneVolumesParamsWithHTTPClient(client *http.Client) *PruneVolumesParams {

	return &PruneVolumesParams{
		HTTPClient: client,
	}
}

/*PruneVolumesParams contains all the parameters to send to the API endpoint
for the prune volumes operation typically these are written to a http.Request
*/
type PruneVolumesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the prune volumes params
func (o *PruneVolumesParams) WithTimeout(timeout time.Duration) *PruneVolumesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the prune volumes params
func (o *PruneVolumesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the prune volumes params
func (o *PruneVolumesParams) WithContext(ctx context.Context) *PruneVolumesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the prune volumes params
func (o *PruneVolumesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the prune volumes params
func (o *PruneVolumesParams) WithHTTPClient(client *http.Client) *PruneVolumesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the prune volumes params
func (o *PruneVolumesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PruneVolumesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
