// Code generated by go-swagger; DO NOT EDIT.

package volumes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/pascomnet/nomad-driver-podman/models"
)

// PruneVolumesReader is a Reader for the PruneVolumes structure.
type PruneVolumesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PruneVolumesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPruneVolumesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewPruneVolumesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPruneVolumesOK creates a PruneVolumesOK with default headers values
func NewPruneVolumesOK() *PruneVolumesOK {
	return &PruneVolumesOK{}
}

/*PruneVolumesOK handles this case with default header values.

Volume prune response
*/
type PruneVolumesOK struct {
	Payload []*models.VolumePruneReport
}

func (o *PruneVolumesOK) Error() string {
	return fmt.Sprintf("[POST /libpod/volumes/prune][%d] pruneVolumesOK  %+v", 200, o.Payload)
}

func (o *PruneVolumesOK) GetPayload() []*models.VolumePruneReport {
	return o.Payload
}

func (o *PruneVolumesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPruneVolumesInternalServerError creates a PruneVolumesInternalServerError with default headers values
func NewPruneVolumesInternalServerError() *PruneVolumesInternalServerError {
	return &PruneVolumesInternalServerError{}
}

/*PruneVolumesInternalServerError handles this case with default header values.

Internal server error
*/
type PruneVolumesInternalServerError struct {
	Payload *PruneVolumesInternalServerErrorBody
}

func (o *PruneVolumesInternalServerError) Error() string {
	return fmt.Sprintf("[POST /libpod/volumes/prune][%d] pruneVolumesInternalServerError  %+v", 500, o.Payload)
}

func (o *PruneVolumesInternalServerError) GetPayload() *PruneVolumesInternalServerErrorBody {
	return o.Payload
}

func (o *PruneVolumesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PruneVolumesInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PruneVolumesInternalServerErrorBody prune volumes internal server error body
swagger:model PruneVolumesInternalServerErrorBody
*/
type PruneVolumesInternalServerErrorBody struct {

	// API root cause formatted for automated parsing
	Because string `json:"cause,omitempty"`

	// human error message, formatted for a human to read
	Message string `json:"message,omitempty"`

	// http response code
	ResponseCode int64 `json:"response,omitempty"`
}

// Validate validates this prune volumes internal server error body
func (o *PruneVolumesInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PruneVolumesInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PruneVolumesInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res PruneVolumesInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
