// Code generated by go-swagger; DO NOT EDIT.

package networks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/pascomnet/nomad-driver-podman/models"
)

// LibpodCreateNetworkReader is a Reader for the LibpodCreateNetwork structure.
type LibpodCreateNetworkReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LibpodCreateNetworkReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLibpodCreateNetworkOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewLibpodCreateNetworkBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewLibpodCreateNetworkInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewLibpodCreateNetworkOK creates a LibpodCreateNetworkOK with default headers values
func NewLibpodCreateNetworkOK() *LibpodCreateNetworkOK {
	return &LibpodCreateNetworkOK{}
}

/*LibpodCreateNetworkOK handles this case with default header values.

Network create
*/
type LibpodCreateNetworkOK struct {
	Payload *models.NetworkCreateReport
}

func (o *LibpodCreateNetworkOK) Error() string {
	return fmt.Sprintf("[POST /libpod/networks/create][%d] libpodCreateNetworkOK  %+v", 200, o.Payload)
}

func (o *LibpodCreateNetworkOK) GetPayload() *models.NetworkCreateReport {
	return o.Payload
}

func (o *LibpodCreateNetworkOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NetworkCreateReport)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLibpodCreateNetworkBadRequest creates a LibpodCreateNetworkBadRequest with default headers values
func NewLibpodCreateNetworkBadRequest() *LibpodCreateNetworkBadRequest {
	return &LibpodCreateNetworkBadRequest{}
}

/*LibpodCreateNetworkBadRequest handles this case with default header values.

Bad parameter in request
*/
type LibpodCreateNetworkBadRequest struct {
	Payload *LibpodCreateNetworkBadRequestBody
}

func (o *LibpodCreateNetworkBadRequest) Error() string {
	return fmt.Sprintf("[POST /libpod/networks/create][%d] libpodCreateNetworkBadRequest  %+v", 400, o.Payload)
}

func (o *LibpodCreateNetworkBadRequest) GetPayload() *LibpodCreateNetworkBadRequestBody {
	return o.Payload
}

func (o *LibpodCreateNetworkBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(LibpodCreateNetworkBadRequestBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLibpodCreateNetworkInternalServerError creates a LibpodCreateNetworkInternalServerError with default headers values
func NewLibpodCreateNetworkInternalServerError() *LibpodCreateNetworkInternalServerError {
	return &LibpodCreateNetworkInternalServerError{}
}

/*LibpodCreateNetworkInternalServerError handles this case with default header values.

Internal server error
*/
type LibpodCreateNetworkInternalServerError struct {
	Payload *LibpodCreateNetworkInternalServerErrorBody
}

func (o *LibpodCreateNetworkInternalServerError) Error() string {
	return fmt.Sprintf("[POST /libpod/networks/create][%d] libpodCreateNetworkInternalServerError  %+v", 500, o.Payload)
}

func (o *LibpodCreateNetworkInternalServerError) GetPayload() *LibpodCreateNetworkInternalServerErrorBody {
	return o.Payload
}

func (o *LibpodCreateNetworkInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(LibpodCreateNetworkInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*LibpodCreateNetworkBadRequestBody libpod create network bad request body
swagger:model LibpodCreateNetworkBadRequestBody
*/
type LibpodCreateNetworkBadRequestBody struct {

	// API root cause formatted for automated parsing
	Because string `json:"cause,omitempty"`

	// human error message, formatted for a human to read
	Message string `json:"message,omitempty"`

	// http response code
	ResponseCode int64 `json:"response,omitempty"`
}

// Validate validates this libpod create network bad request body
func (o *LibpodCreateNetworkBadRequestBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *LibpodCreateNetworkBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *LibpodCreateNetworkBadRequestBody) UnmarshalBinary(b []byte) error {
	var res LibpodCreateNetworkBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*LibpodCreateNetworkInternalServerErrorBody libpod create network internal server error body
swagger:model LibpodCreateNetworkInternalServerErrorBody
*/
type LibpodCreateNetworkInternalServerErrorBody struct {

	// API root cause formatted for automated parsing
	Because string `json:"cause,omitempty"`

	// human error message, formatted for a human to read
	Message string `json:"message,omitempty"`

	// http response code
	ResponseCode int64 `json:"response,omitempty"`
}

// Validate validates this libpod create network internal server error body
func (o *LibpodCreateNetworkInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *LibpodCreateNetworkInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *LibpodCreateNetworkInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res LibpodCreateNetworkInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
