// Code generated by go-swagger; DO NOT EDIT.

package networks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/pascomnet/nomad-driver-podman/models"
)

// LibpodInspectNetworkReader is a Reader for the LibpodInspectNetwork structure.
type LibpodInspectNetworkReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LibpodInspectNetworkReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLibpodInspectNetworkOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewLibpodInspectNetworkNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewLibpodInspectNetworkInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewLibpodInspectNetworkOK creates a LibpodInspectNetworkOK with default headers values
func NewLibpodInspectNetworkOK() *LibpodInspectNetworkOK {
	return &LibpodInspectNetworkOK{}
}

/*LibpodInspectNetworkOK handles this case with default header values.

Network inspect
*/
type LibpodInspectNetworkOK struct {
	Payload []models.NetworkInspectReport
}

func (o *LibpodInspectNetworkOK) Error() string {
	return fmt.Sprintf("[GET /libpod/networks/{name}/json][%d] libpodInspectNetworkOK  %+v", 200, o.Payload)
}

func (o *LibpodInspectNetworkOK) GetPayload() []models.NetworkInspectReport {
	return o.Payload
}

func (o *LibpodInspectNetworkOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLibpodInspectNetworkNotFound creates a LibpodInspectNetworkNotFound with default headers values
func NewLibpodInspectNetworkNotFound() *LibpodInspectNetworkNotFound {
	return &LibpodInspectNetworkNotFound{}
}

/*LibpodInspectNetworkNotFound handles this case with default header values.

No such network
*/
type LibpodInspectNetworkNotFound struct {
	Payload *LibpodInspectNetworkNotFoundBody
}

func (o *LibpodInspectNetworkNotFound) Error() string {
	return fmt.Sprintf("[GET /libpod/networks/{name}/json][%d] libpodInspectNetworkNotFound  %+v", 404, o.Payload)
}

func (o *LibpodInspectNetworkNotFound) GetPayload() *LibpodInspectNetworkNotFoundBody {
	return o.Payload
}

func (o *LibpodInspectNetworkNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(LibpodInspectNetworkNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLibpodInspectNetworkInternalServerError creates a LibpodInspectNetworkInternalServerError with default headers values
func NewLibpodInspectNetworkInternalServerError() *LibpodInspectNetworkInternalServerError {
	return &LibpodInspectNetworkInternalServerError{}
}

/*LibpodInspectNetworkInternalServerError handles this case with default header values.

Internal server error
*/
type LibpodInspectNetworkInternalServerError struct {
	Payload *LibpodInspectNetworkInternalServerErrorBody
}

func (o *LibpodInspectNetworkInternalServerError) Error() string {
	return fmt.Sprintf("[GET /libpod/networks/{name}/json][%d] libpodInspectNetworkInternalServerError  %+v", 500, o.Payload)
}

func (o *LibpodInspectNetworkInternalServerError) GetPayload() *LibpodInspectNetworkInternalServerErrorBody {
	return o.Payload
}

func (o *LibpodInspectNetworkInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(LibpodInspectNetworkInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*LibpodInspectNetworkInternalServerErrorBody libpod inspect network internal server error body
swagger:model LibpodInspectNetworkInternalServerErrorBody
*/
type LibpodInspectNetworkInternalServerErrorBody struct {

	// API root cause formatted for automated parsing
	Because string `json:"cause,omitempty"`

	// human error message, formatted for a human to read
	Message string `json:"message,omitempty"`

	// http response code
	ResponseCode int64 `json:"response,omitempty"`
}

// Validate validates this libpod inspect network internal server error body
func (o *LibpodInspectNetworkInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *LibpodInspectNetworkInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *LibpodInspectNetworkInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res LibpodInspectNetworkInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*LibpodInspectNetworkNotFoundBody libpod inspect network not found body
swagger:model LibpodInspectNetworkNotFoundBody
*/
type LibpodInspectNetworkNotFoundBody struct {

	// API root cause formatted for automated parsing
	Because string `json:"cause,omitempty"`

	// human error message, formatted for a human to read
	Message string `json:"message,omitempty"`

	// http response code
	ResponseCode int64 `json:"response,omitempty"`
}

// Validate validates this libpod inspect network not found body
func (o *LibpodInspectNetworkNotFoundBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *LibpodInspectNetworkNotFoundBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *LibpodInspectNetworkNotFoundBody) UnmarshalBinary(b []byte) error {
	var res LibpodInspectNetworkNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
