// Code generated by go-swagger; DO NOT EDIT.

package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewLibpodGetInfoParams creates a new LibpodGetInfoParams object
// with the default values initialized.
func NewLibpodGetInfoParams() *LibpodGetInfoParams {

	return &LibpodGetInfoParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewLibpodGetInfoParamsWithTimeout creates a new LibpodGetInfoParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewLibpodGetInfoParamsWithTimeout(timeout time.Duration) *LibpodGetInfoParams {

	return &LibpodGetInfoParams{

		timeout: timeout,
	}
}

// NewLibpodGetInfoParamsWithContext creates a new LibpodGetInfoParams object
// with the default values initialized, and the ability to set a context for a request
func NewLibpodGetInfoParamsWithContext(ctx context.Context) *LibpodGetInfoParams {

	return &LibpodGetInfoParams{

		Context: ctx,
	}
}

// NewLibpodGetInfoParamsWithHTTPClient creates a new LibpodGetInfoParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewLibpodGetInfoParamsWithHTTPClient(client *http.Client) *LibpodGetInfoParams {

	return &LibpodGetInfoParams{
		HTTPClient: client,
	}
}

/*LibpodGetInfoParams contains all the parameters to send to the API endpoint
for the libpod get info operation typically these are written to a http.Request
*/
type LibpodGetInfoParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the libpod get info params
func (o *LibpodGetInfoParams) WithTimeout(timeout time.Duration) *LibpodGetInfoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the libpod get info params
func (o *LibpodGetInfoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the libpod get info params
func (o *LibpodGetInfoParams) WithContext(ctx context.Context) *LibpodGetInfoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the libpod get info params
func (o *LibpodGetInfoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the libpod get info params
func (o *LibpodGetInfoParams) WithHTTPClient(client *http.Client) *LibpodGetInfoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the libpod get info params
func (o *LibpodGetInfoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *LibpodGetInfoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
