// Code generated by go-swagger; DO NOT EDIT.

package containers_compat

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPruneContainersParams creates a new PruneContainersParams object
// with the default values initialized.
func NewPruneContainersParams() *PruneContainersParams {
	var ()
	return &PruneContainersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPruneContainersParamsWithTimeout creates a new PruneContainersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPruneContainersParamsWithTimeout(timeout time.Duration) *PruneContainersParams {
	var ()
	return &PruneContainersParams{

		timeout: timeout,
	}
}

// NewPruneContainersParamsWithContext creates a new PruneContainersParams object
// with the default values initialized, and the ability to set a context for a request
func NewPruneContainersParamsWithContext(ctx context.Context) *PruneContainersParams {
	var ()
	return &PruneContainersParams{

		Context: ctx,
	}
}

// NewPruneContainersParamsWithHTTPClient creates a new PruneContainersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPruneContainersParamsWithHTTPClient(client *http.Client) *PruneContainersParams {
	var ()
	return &PruneContainersParams{
		HTTPClient: client,
	}
}

/*PruneContainersParams contains all the parameters to send to the API endpoint
for the prune containers operation typically these are written to a http.Request
*/
type PruneContainersParams struct {

	/*Filters
	 Filters to process on the prune list, encoded as JSON (a `map[string][]string`).  Available filters:
	- `until=<timestamp>` Prune containers created before this timestamp. The `<timestamp>` can be Unix timestamps, date formatted timestamps, or Go duration strings (e.g. `10m`, `1h30m`) computed relative to the daemon machine’s time.
	- `label` (`label=<key>`, `label=<key>=<value>`, `label!=<key>`, or `label!=<key>=<value>`) Prune containers with (or without, in case `label!=...` is used) the specified labels.


	*/
	Filters *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the prune containers params
func (o *PruneContainersParams) WithTimeout(timeout time.Duration) *PruneContainersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the prune containers params
func (o *PruneContainersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the prune containers params
func (o *PruneContainersParams) WithContext(ctx context.Context) *PruneContainersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the prune containers params
func (o *PruneContainersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the prune containers params
func (o *PruneContainersParams) WithHTTPClient(client *http.Client) *PruneContainersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the prune containers params
func (o *PruneContainersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFilters adds the filters to the prune containers params
func (o *PruneContainersParams) WithFilters(filters *string) *PruneContainersParams {
	o.SetFilters(filters)
	return o
}

// SetFilters adds the filters to the prune containers params
func (o *PruneContainersParams) SetFilters(filters *string) {
	o.Filters = filters
}

// WriteToRequest writes these params to a swagger request
func (o *PruneContainersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Filters != nil {

		// query param filters
		var qrFilters string
		if o.Filters != nil {
			qrFilters = *o.Filters
		}
		qFilters := qrFilters
		if qFilters != "" {
			if err := r.SetQueryParam("filters", qFilters); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
