// Code generated by go-swagger; DO NOT EDIT.

package containers_compat

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewStartContainerParams creates a new StartContainerParams object
// with the default values initialized.
func NewStartContainerParams() *StartContainerParams {
	var (
		detachKeysDefault = string("ctrl-p,ctrl-q")
	)
	return &StartContainerParams{
		DetachKeys: &detachKeysDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewStartContainerParamsWithTimeout creates a new StartContainerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewStartContainerParamsWithTimeout(timeout time.Duration) *StartContainerParams {
	var (
		detachKeysDefault = string("ctrl-p,ctrl-q")
	)
	return &StartContainerParams{
		DetachKeys: &detachKeysDefault,

		timeout: timeout,
	}
}

// NewStartContainerParamsWithContext creates a new StartContainerParams object
// with the default values initialized, and the ability to set a context for a request
func NewStartContainerParamsWithContext(ctx context.Context) *StartContainerParams {
	var (
		detachKeysDefault = string("ctrl-p,ctrl-q")
	)
	return &StartContainerParams{
		DetachKeys: &detachKeysDefault,

		Context: ctx,
	}
}

// NewStartContainerParamsWithHTTPClient creates a new StartContainerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewStartContainerParamsWithHTTPClient(client *http.Client) *StartContainerParams {
	var (
		detachKeysDefault = string("ctrl-p,ctrl-q")
	)
	return &StartContainerParams{
		DetachKeys: &detachKeysDefault,
		HTTPClient: client,
	}
}

/*StartContainerParams contains all the parameters to send to the API endpoint
for the start container operation typically these are written to a http.Request
*/
type StartContainerParams struct {

	/*DetachKeys
	  Override the key sequence for detaching a container. Format is a single character [a-Z] or ctrl-<value> where <value> is one of: a-z, @, ^, [, , or _.

	*/
	DetachKeys *string
	/*Name
	  the name or ID of the container

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the start container params
func (o *StartContainerParams) WithTimeout(timeout time.Duration) *StartContainerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the start container params
func (o *StartContainerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the start container params
func (o *StartContainerParams) WithContext(ctx context.Context) *StartContainerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the start container params
func (o *StartContainerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the start container params
func (o *StartContainerParams) WithHTTPClient(client *http.Client) *StartContainerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the start container params
func (o *StartContainerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDetachKeys adds the detachKeys to the start container params
func (o *StartContainerParams) WithDetachKeys(detachKeys *string) *StartContainerParams {
	o.SetDetachKeys(detachKeys)
	return o
}

// SetDetachKeys adds the detachKeys to the start container params
func (o *StartContainerParams) SetDetachKeys(detachKeys *string) {
	o.DetachKeys = detachKeys
}

// WithName adds the name to the start container params
func (o *StartContainerParams) WithName(name string) *StartContainerParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the start container params
func (o *StartContainerParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *StartContainerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.DetachKeys != nil {

		// query param detachKeys
		var qrDetachKeys string
		if o.DetachKeys != nil {
			qrDetachKeys = *o.DetachKeys
		}
		qDetachKeys := qrDetachKeys
		if qDetachKeys != "" {
			if err := r.SetQueryParam("detachKeys", qDetachKeys); err != nil {
				return err
			}
		}

	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
