// Code generated by go-swagger; DO NOT EDIT.

package containers_compat

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewTopContainerParams creates a new TopContainerParams object
// with the default values initialized.
func NewTopContainerParams() *TopContainerParams {
	var ()
	return &TopContainerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewTopContainerParamsWithTimeout creates a new TopContainerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTopContainerParamsWithTimeout(timeout time.Duration) *TopContainerParams {
	var ()
	return &TopContainerParams{

		timeout: timeout,
	}
}

// NewTopContainerParamsWithContext creates a new TopContainerParams object
// with the default values initialized, and the ability to set a context for a request
func NewTopContainerParamsWithContext(ctx context.Context) *TopContainerParams {
	var ()
	return &TopContainerParams{

		Context: ctx,
	}
}

// NewTopContainerParamsWithHTTPClient creates a new TopContainerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewTopContainerParamsWithHTTPClient(client *http.Client) *TopContainerParams {
	var ()
	return &TopContainerParams{
		HTTPClient: client,
	}
}

/*TopContainerParams contains all the parameters to send to the API endpoint
for the top container operation typically these are written to a http.Request
*/
type TopContainerParams struct {

	/*Name
	  the name or ID of the container

	*/
	Name string
	/*PsArgs
	  arguments to pass to ps such as aux. Requires ps(1) to be installed in the container if no ps(1) compatible AIX descriptors are used.

	*/
	PsArgs *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the top container params
func (o *TopContainerParams) WithTimeout(timeout time.Duration) *TopContainerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the top container params
func (o *TopContainerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the top container params
func (o *TopContainerParams) WithContext(ctx context.Context) *TopContainerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the top container params
func (o *TopContainerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the top container params
func (o *TopContainerParams) WithHTTPClient(client *http.Client) *TopContainerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the top container params
func (o *TopContainerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the top container params
func (o *TopContainerParams) WithName(name string) *TopContainerParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the top container params
func (o *TopContainerParams) SetName(name string) {
	o.Name = name
}

// WithPsArgs adds the psArgs to the top container params
func (o *TopContainerParams) WithPsArgs(psArgs *string) *TopContainerParams {
	o.SetPsArgs(psArgs)
	return o
}

// SetPsArgs adds the psArgs to the top container params
func (o *TopContainerParams) SetPsArgs(psArgs *string) {
	o.PsArgs = psArgs
}

// WriteToRequest writes these params to a swagger request
func (o *TopContainerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if o.PsArgs != nil {

		// query param ps_args
		var qrPsArgs string
		if o.PsArgs != nil {
			qrPsArgs = *o.PsArgs
		}
		qPsArgs := qrPsArgs
		if qPsArgs != "" {
			if err := r.SetQueryParam("ps_args", qPsArgs); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
