// Code generated by go-swagger; DO NOT EDIT.

package containers_compat

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUnpauseContainerParams creates a new UnpauseContainerParams object
// with the default values initialized.
func NewUnpauseContainerParams() *UnpauseContainerParams {
	var ()
	return &UnpauseContainerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUnpauseContainerParamsWithTimeout creates a new UnpauseContainerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUnpauseContainerParamsWithTimeout(timeout time.Duration) *UnpauseContainerParams {
	var ()
	return &UnpauseContainerParams{

		timeout: timeout,
	}
}

// NewUnpauseContainerParamsWithContext creates a new UnpauseContainerParams object
// with the default values initialized, and the ability to set a context for a request
func NewUnpauseContainerParamsWithContext(ctx context.Context) *UnpauseContainerParams {
	var ()
	return &UnpauseContainerParams{

		Context: ctx,
	}
}

// NewUnpauseContainerParamsWithHTTPClient creates a new UnpauseContainerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUnpauseContainerParamsWithHTTPClient(client *http.Client) *UnpauseContainerParams {
	var ()
	return &UnpauseContainerParams{
		HTTPClient: client,
	}
}

/*UnpauseContainerParams contains all the parameters to send to the API endpoint
for the unpause container operation typically these are written to a http.Request
*/
type UnpauseContainerParams struct {

	/*Name
	  the name or ID of the container

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the unpause container params
func (o *UnpauseContainerParams) WithTimeout(timeout time.Duration) *UnpauseContainerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the unpause container params
func (o *UnpauseContainerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the unpause container params
func (o *UnpauseContainerParams) WithContext(ctx context.Context) *UnpauseContainerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the unpause container params
func (o *UnpauseContainerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the unpause container params
func (o *UnpauseContainerParams) WithHTTPClient(client *http.Client) *UnpauseContainerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the unpause container params
func (o *UnpauseContainerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the unpause container params
func (o *UnpauseContainerParams) WithName(name string) *UnpauseContainerParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the unpause container params
func (o *UnpauseContainerParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *UnpauseContainerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
