// Code generated by go-swagger; DO NOT EDIT.

package images_compat

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewExportImageParams creates a new ExportImageParams object
// with the default values initialized.
func NewExportImageParams() *ExportImageParams {
	var ()
	return &ExportImageParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewExportImageParamsWithTimeout creates a new ExportImageParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewExportImageParamsWithTimeout(timeout time.Duration) *ExportImageParams {
	var ()
	return &ExportImageParams{

		timeout: timeout,
	}
}

// NewExportImageParamsWithContext creates a new ExportImageParams object
// with the default values initialized, and the ability to set a context for a request
func NewExportImageParamsWithContext(ctx context.Context) *ExportImageParams {
	var ()
	return &ExportImageParams{

		Context: ctx,
	}
}

// NewExportImageParamsWithHTTPClient creates a new ExportImageParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewExportImageParamsWithHTTPClient(client *http.Client) *ExportImageParams {
	var ()
	return &ExportImageParams{
		HTTPClient: client,
	}
}

/*ExportImageParams contains all the parameters to send to the API endpoint
for the export image operation typically these are written to a http.Request
*/
type ExportImageParams struct {

	/*Name
	  the name or ID of the container

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the export image params
func (o *ExportImageParams) WithTimeout(timeout time.Duration) *ExportImageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the export image params
func (o *ExportImageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the export image params
func (o *ExportImageParams) WithContext(ctx context.Context) *ExportImageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the export image params
func (o *ExportImageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the export image params
func (o *ExportImageParams) WithHTTPClient(client *http.Client) *ExportImageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the export image params
func (o *ExportImageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the export image params
func (o *ExportImageParams) WithName(name string) *ExportImageParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the export image params
func (o *ExportImageParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *ExportImageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name:.*
	if err := r.SetPathParam("name:.*", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
