// Code generated by go-swagger; DO NOT EDIT.

package images_compat

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewListImagesParams creates a new ListImagesParams object
// with the default values initialized.
func NewListImagesParams() *ListImagesParams {
	var (
		allDefault     = bool(false)
		digestsDefault = bool(false)
	)
	return &ListImagesParams{
		All:     &allDefault,
		Digests: &digestsDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewListImagesParamsWithTimeout creates a new ListImagesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListImagesParamsWithTimeout(timeout time.Duration) *ListImagesParams {
	var (
		allDefault     = bool(false)
		digestsDefault = bool(false)
	)
	return &ListImagesParams{
		All:     &allDefault,
		Digests: &digestsDefault,

		timeout: timeout,
	}
}

// NewListImagesParamsWithContext creates a new ListImagesParams object
// with the default values initialized, and the ability to set a context for a request
func NewListImagesParamsWithContext(ctx context.Context) *ListImagesParams {
	var (
		allDefault     = bool(false)
		digestsDefault = bool(false)
	)
	return &ListImagesParams{
		All:     &allDefault,
		Digests: &digestsDefault,

		Context: ctx,
	}
}

// NewListImagesParamsWithHTTPClient creates a new ListImagesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListImagesParamsWithHTTPClient(client *http.Client) *ListImagesParams {
	var (
		allDefault     = bool(false)
		digestsDefault = bool(false)
	)
	return &ListImagesParams{
		All:        &allDefault,
		Digests:    &digestsDefault,
		HTTPClient: client,
	}
}

/*ListImagesParams contains all the parameters to send to the API endpoint
for the list images operation typically these are written to a http.Request
*/
type ListImagesParams struct {

	/*All
	  Show all images. Only images from a final layer (no children) are shown by default.

	*/
	All *bool
	/*Digests
	  Not supported

	*/
	Digests *bool
	/*Filters
	  A JSON encoded value of the filters (a `map[string][]string`) to process on the images list. Available filters:
	- `before`=(`<image-name>[:<tag>]`,  `<image id>` or `<image@digest>`)
	- `dangling=true`
	- `label=key` or `label="key=value"` of an image label
	- `reference`=(`<image-name>[:<tag>]`)
	- `since`=(`<image-name>[:<tag>]`,  `<image id>` or `<image@digest>`)


	*/
	Filters *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list images params
func (o *ListImagesParams) WithTimeout(timeout time.Duration) *ListImagesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list images params
func (o *ListImagesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list images params
func (o *ListImagesParams) WithContext(ctx context.Context) *ListImagesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list images params
func (o *ListImagesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list images params
func (o *ListImagesParams) WithHTTPClient(client *http.Client) *ListImagesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list images params
func (o *ListImagesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAll adds the all to the list images params
func (o *ListImagesParams) WithAll(all *bool) *ListImagesParams {
	o.SetAll(all)
	return o
}

// SetAll adds the all to the list images params
func (o *ListImagesParams) SetAll(all *bool) {
	o.All = all
}

// WithDigests adds the digests to the list images params
func (o *ListImagesParams) WithDigests(digests *bool) *ListImagesParams {
	o.SetDigests(digests)
	return o
}

// SetDigests adds the digests to the list images params
func (o *ListImagesParams) SetDigests(digests *bool) {
	o.Digests = digests
}

// WithFilters adds the filters to the list images params
func (o *ListImagesParams) WithFilters(filters *string) *ListImagesParams {
	o.SetFilters(filters)
	return o
}

// SetFilters adds the filters to the list images params
func (o *ListImagesParams) SetFilters(filters *string) {
	o.Filters = filters
}

// WriteToRequest writes these params to a swagger request
func (o *ListImagesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.All != nil {

		// query param all
		var qrAll bool
		if o.All != nil {
			qrAll = *o.All
		}
		qAll := swag.FormatBool(qrAll)
		if qAll != "" {
			if err := r.SetQueryParam("all", qAll); err != nil {
				return err
			}
		}

	}

	if o.Digests != nil {

		// query param digests
		var qrDigests bool
		if o.Digests != nil {
			qrDigests = *o.Digests
		}
		qDigests := swag.FormatBool(qrDigests)
		if qDigests != "" {
			if err := r.SetQueryParam("digests", qDigests); err != nil {
				return err
			}
		}

	}

	if o.Filters != nil {

		// query param filters
		var qrFilters string
		if o.Filters != nil {
			qrFilters = *o.Filters
		}
		qFilters := qrFilters
		if qFilters != "" {
			if err := r.SetQueryParam("filters", qFilters); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
