// Code generated by go-swagger; DO NOT EDIT.

package images_compat

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPushImageParams creates a new PushImageParams object
// with the default values initialized.
func NewPushImageParams() *PushImageParams {
	var ()
	return &PushImageParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPushImageParamsWithTimeout creates a new PushImageParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPushImageParamsWithTimeout(timeout time.Duration) *PushImageParams {
	var ()
	return &PushImageParams{

		timeout: timeout,
	}
}

// NewPushImageParamsWithContext creates a new PushImageParams object
// with the default values initialized, and the ability to set a context for a request
func NewPushImageParamsWithContext(ctx context.Context) *PushImageParams {
	var ()
	return &PushImageParams{

		Context: ctx,
	}
}

// NewPushImageParamsWithHTTPClient creates a new PushImageParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPushImageParamsWithHTTPClient(client *http.Client) *PushImageParams {
	var ()
	return &PushImageParams{
		HTTPClient: client,
	}
}

/*PushImageParams contains all the parameters to send to the API endpoint
for the push image operation typically these are written to a http.Request
*/
type PushImageParams struct {

	/*XRegistryAuth
	  A base64-encoded auth configuration.

	*/
	XRegistryAuth *string
	/*Name
	  Name of image to push.

	*/
	Name string
	/*Tag
	  The tag to associate with the image on the registry.

	*/
	Tag *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the push image params
func (o *PushImageParams) WithTimeout(timeout time.Duration) *PushImageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the push image params
func (o *PushImageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the push image params
func (o *PushImageParams) WithContext(ctx context.Context) *PushImageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the push image params
func (o *PushImageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the push image params
func (o *PushImageParams) WithHTTPClient(client *http.Client) *PushImageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the push image params
func (o *PushImageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXRegistryAuth adds the xRegistryAuth to the push image params
func (o *PushImageParams) WithXRegistryAuth(xRegistryAuth *string) *PushImageParams {
	o.SetXRegistryAuth(xRegistryAuth)
	return o
}

// SetXRegistryAuth adds the xRegistryAuth to the push image params
func (o *PushImageParams) SetXRegistryAuth(xRegistryAuth *string) {
	o.XRegistryAuth = xRegistryAuth
}

// WithName adds the name to the push image params
func (o *PushImageParams) WithName(name string) *PushImageParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the push image params
func (o *PushImageParams) SetName(name string) {
	o.Name = name
}

// WithTag adds the tag to the push image params
func (o *PushImageParams) WithTag(tag *string) *PushImageParams {
	o.SetTag(tag)
	return o
}

// SetTag adds the tag to the push image params
func (o *PushImageParams) SetTag(tag *string) {
	o.Tag = tag
}

// WriteToRequest writes these params to a swagger request
func (o *PushImageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XRegistryAuth != nil {

		// header param X-Registry-Auth
		if err := r.SetHeaderParam("X-Registry-Auth", *o.XRegistryAuth); err != nil {
			return err
		}

	}

	// path param name:.*
	if err := r.SetPathParam("name:.*", o.Name); err != nil {
		return err
	}

	if o.Tag != nil {

		// query param tag
		var qrTag string
		if o.Tag != nil {
			qrTag = *o.Tag
		}
		qTag := qrTag
		if qTag != "" {
			if err := r.SetQueryParam("tag", qTag); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
