// Code generated by go-swagger; DO NOT EDIT.

package images_compat

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewSearchImagesParams creates a new SearchImagesParams object
// with the default values initialized.
func NewSearchImagesParams() *SearchImagesParams {
	var ()
	return &SearchImagesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSearchImagesParamsWithTimeout creates a new SearchImagesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSearchImagesParamsWithTimeout(timeout time.Duration) *SearchImagesParams {
	var ()
	return &SearchImagesParams{

		timeout: timeout,
	}
}

// NewSearchImagesParamsWithContext creates a new SearchImagesParams object
// with the default values initialized, and the ability to set a context for a request
func NewSearchImagesParamsWithContext(ctx context.Context) *SearchImagesParams {
	var ()
	return &SearchImagesParams{

		Context: ctx,
	}
}

// NewSearchImagesParamsWithHTTPClient creates a new SearchImagesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSearchImagesParamsWithHTTPClient(client *http.Client) *SearchImagesParams {
	var ()
	return &SearchImagesParams{
		HTTPClient: client,
	}
}

/*SearchImagesParams contains all the parameters to send to the API endpoint
for the search images operation typically these are written to a http.Request
*/
type SearchImagesParams struct {

	/*Filters
	  A JSON encoded value of the filters (a `map[string][]string`) to process on the images list. Available filters:
	- `is-automated=(true|false)`
	- `is-official=(true|false)`
	- `stars=<number>` Matches images that has at least 'number' stars.


	*/
	Filters *string
	/*Limit
	  maximum number of results

	*/
	Limit *int64
	/*Term
	  term to search

	*/
	Term *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the search images params
func (o *SearchImagesParams) WithTimeout(timeout time.Duration) *SearchImagesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the search images params
func (o *SearchImagesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the search images params
func (o *SearchImagesParams) WithContext(ctx context.Context) *SearchImagesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the search images params
func (o *SearchImagesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the search images params
func (o *SearchImagesParams) WithHTTPClient(client *http.Client) *SearchImagesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the search images params
func (o *SearchImagesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFilters adds the filters to the search images params
func (o *SearchImagesParams) WithFilters(filters *string) *SearchImagesParams {
	o.SetFilters(filters)
	return o
}

// SetFilters adds the filters to the search images params
func (o *SearchImagesParams) SetFilters(filters *string) {
	o.Filters = filters
}

// WithLimit adds the limit to the search images params
func (o *SearchImagesParams) WithLimit(limit *int64) *SearchImagesParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the search images params
func (o *SearchImagesParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithTerm adds the term to the search images params
func (o *SearchImagesParams) WithTerm(term *string) *SearchImagesParams {
	o.SetTerm(term)
	return o
}

// SetTerm adds the term to the search images params
func (o *SearchImagesParams) SetTerm(term *string) {
	o.Term = term
}

// WriteToRequest writes these params to a swagger request
func (o *SearchImagesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Filters != nil {

		// query param filters
		var qrFilters string
		if o.Filters != nil {
			qrFilters = *o.Filters
		}
		qFilters := qrFilters
		if qFilters != "" {
			if err := r.SetQueryParam("filters", qFilters); err != nil {
				return err
			}
		}

	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Term != nil {

		// query param term
		var qrTerm string
		if o.Term != nil {
			qrTerm = *o.Term
		}
		qTerm := qrTerm
		if qTerm != "" {
			if err := r.SetQueryParam("term", qTerm); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
