// Code generated by go-swagger; DO NOT EDIT.

package networks_compat

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/pascomnet/nomad-driver-podman/models"
)

// NewCompatCreateNetworkParams creates a new CompatCreateNetworkParams object
// with the default values initialized.
func NewCompatCreateNetworkParams() *CompatCreateNetworkParams {
	var ()
	return &CompatCreateNetworkParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCompatCreateNetworkParamsWithTimeout creates a new CompatCreateNetworkParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCompatCreateNetworkParamsWithTimeout(timeout time.Duration) *CompatCreateNetworkParams {
	var ()
	return &CompatCreateNetworkParams{

		timeout: timeout,
	}
}

// NewCompatCreateNetworkParamsWithContext creates a new CompatCreateNetworkParams object
// with the default values initialized, and the ability to set a context for a request
func NewCompatCreateNetworkParamsWithContext(ctx context.Context) *CompatCreateNetworkParams {
	var ()
	return &CompatCreateNetworkParams{

		Context: ctx,
	}
}

// NewCompatCreateNetworkParamsWithHTTPClient creates a new CompatCreateNetworkParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCompatCreateNetworkParamsWithHTTPClient(client *http.Client) *CompatCreateNetworkParams {
	var ()
	return &CompatCreateNetworkParams{
		HTTPClient: client,
	}
}

/*CompatCreateNetworkParams contains all the parameters to send to the API endpoint
for the compat create network operation typically these are written to a http.Request
*/
type CompatCreateNetworkParams struct {

	/*Create
	  attributes for creating a container

	*/
	Create *models.NetworkCreateRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the compat create network params
func (o *CompatCreateNetworkParams) WithTimeout(timeout time.Duration) *CompatCreateNetworkParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the compat create network params
func (o *CompatCreateNetworkParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the compat create network params
func (o *CompatCreateNetworkParams) WithContext(ctx context.Context) *CompatCreateNetworkParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the compat create network params
func (o *CompatCreateNetworkParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the compat create network params
func (o *CompatCreateNetworkParams) WithHTTPClient(client *http.Client) *CompatCreateNetworkParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the compat create network params
func (o *CompatCreateNetworkParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCreate adds the create to the compat create network params
func (o *CompatCreateNetworkParams) WithCreate(create *models.NetworkCreateRequest) *CompatCreateNetworkParams {
	o.SetCreate(create)
	return o
}

// SetCreate adds the create to the compat create network params
func (o *CompatCreateNetworkParams) SetCreate(create *models.NetworkCreateRequest) {
	o.Create = create
}

// WriteToRequest writes these params to a swagger request
func (o *CompatCreateNetworkParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Create != nil {
		if err := r.SetBodyParam(o.Create); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
