// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// CgroupSpec CgroupSpec represents the cgroup to use for the container.
//
// swagger:model CgroupSpec
type CgroupSpec string

// Validate validates this cgroup spec
func (m CgroupSpec) Validate(formats strfmt.Registry) error {
	return nil
}
