// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// CgroupnsMode CgroupnsMode represents the cgroup namespace mode of the container
//
// swagger:model CgroupnsMode
type CgroupnsMode string

// Validate validates this cgroupns mode
func (m CgroupnsMode) Validate(formats strfmt.Registry) error {
	return nil
}
