// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ContainerStore ContainerStore describes the quantity of containers in the
// store by status
//
// swagger:model ContainerStore
type ContainerStore struct {

	// number
	Number int64 `json:"number,omitempty"`

	// paused
	Paused int64 `json:"paused,omitempty"`

	// running
	Running int64 `json:"running,omitempty"`

	// stopped
	Stopped int64 `json:"stopped,omitempty"`
}

// Validate validates this container store
func (m *ContainerStore) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ContainerStore) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ContainerStore) UnmarshalBinary(b []byte) error {
	var res ContainerStore
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
