// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeviceRequest DeviceRequest represents a request for devices from a device driver.
//
// Used by GPU device drivers.
//
// swagger:model DeviceRequest
type DeviceRequest struct {

	// capabilities
	Capabilities [][]string `json:"Capabilities"`

	// count
	Count int64 `json:"Count,omitempty"`

	// device i ds
	DeviceIDs []string `json:"DeviceIDs"`

	// driver
	Driver string `json:"Driver,omitempty"`

	// options
	Options map[string]string `json:"Options,omitempty"`
}

// Validate validates this device request
func (m *DeviceRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DeviceRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeviceRequest) UnmarshalBinary(b []byte) error {
	var res DeviceRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
