// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeviceMapping DeviceMapping represents the device mapping between the host and the container.
//
// swagger:model DeviceMapping
type DeviceMapping struct {

	// cgroup permissions
	CgroupPermissions string `json:"CgroupPermissions,omitempty"`

	// path in container
	PathInContainer string `json:"PathInContainer,omitempty"`

	// path on host
	PathOnHost string `json:"PathOnHost,omitempty"`
}

// Validate validates this device mapping
func (m *DeviceMapping) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DeviceMapping) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeviceMapping) UnmarshalBinary(b []byte) error {
	var res DeviceMapping
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
