// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EndpointResource EndpointResource contains network resources allocated and used for a container in a network
//
// swagger:model EndpointResource
type EndpointResource struct {

	// endpoint ID
	EndpointID string `json:"EndpointID,omitempty"`

	// IPv4 address
	IPV4Address string `json:"IPv4Address,omitempty"`

	// IPv6 address
	IPV6Address string `json:"IPv6Address,omitempty"`

	// mac address
	MacAddress string `json:"MacAddress,omitempty"`

	// name
	Name string `json:"Name,omitempty"`
}

// Validate validates this endpoint resource
func (m *EndpointResource) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EndpointResource) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EndpointResource) UnmarshalBinary(b []byte) error {
	var res EndpointResource
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
