// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InspectUlimit InspectUlimit is a ulimit that will be applied to the container.
//
// swagger:model InspectUlimit
type InspectUlimit struct {

	// Hard is the hard limit that will be applied.
	Hard uint64 `json:"Hard,omitempty"`

	// Name is the name (type) of the ulimit.
	Name string `json:"Name,omitempty"`

	// Soft is the soft limit that will be applied.
	Soft uint64 `json:"Soft,omitempty"`
}

// Validate validates this inspect ulimit
func (m *InspectUlimit) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InspectUlimit) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InspectUlimit) UnmarshalBinary(b []byte) error {
	var res InspectUlimit
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
