// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ListContainer Listcontainer describes a container suitable for listing
//
// swagger:model ListContainer
type ListContainer struct {

	// Container command
	Command []string `json:"Command"`

	// Container creation time
	Created int64 `json:"Created,omitempty"`

	// If container has exited, the return code from the command
	ExitCode int32 `json:"ExitCode,omitempty"`

	// If container has exited/stopped
	Exited bool `json:"Exited,omitempty"`

	// Time container exited
	ExitedAt int64 `json:"ExitedAt,omitempty"`

	// The unique identifier for the container
	ID string `json:"Id,omitempty"`

	// Container image
	Image string `json:"Image,omitempty"`

	// Container image ID
	ImageID string `json:"ImageID,omitempty"`

	// If this container is a Pod infra container
	IsInfra bool `json:"IsInfra,omitempty"`

	// Labels for container
	Labels map[string]string `json:"Labels,omitempty"`

	// User volume mounts
	Mounts []string `json:"Mounts"`

	// The names assigned to the container
	Names []string `json:"Names"`

	// namespaces
	Namespaces *ListContainerNamespaces `json:"Namespaces,omitempty"`

	// The process id of the container
	Pid int64 `json:"Pid,omitempty"`

	// If the container is part of Pod, the Pod ID. Requires the pod
	// boolean to be set
	Pod string `json:"Pod,omitempty"`

	// If the container is part of Pod, the Pod name. Requires the pod
	// boolean to be set
	PodName string `json:"PodName,omitempty"`

	// Port mappings
	Ports []*PortMapping `json:"Ports"`

	// size
	Size *ContainerSize `json:"Size,omitempty"`

	// Time when container started
	StartedAt int64 `json:"StartedAt,omitempty"`

	// State of container
	State string `json:"State,omitempty"`
}

// Validate validates this list container
func (m *ListContainer) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNamespaces(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePorts(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSize(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ListContainer) validateNamespaces(formats strfmt.Registry) error {

	if swag.IsZero(m.Namespaces) { // not required
		return nil
	}

	if m.Namespaces != nil {
		if err := m.Namespaces.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Namespaces")
			}
			return err
		}
	}

	return nil
}

func (m *ListContainer) validatePorts(formats strfmt.Registry) error {

	if swag.IsZero(m.Ports) { // not required
		return nil
	}

	for i := 0; i < len(m.Ports); i++ {
		if swag.IsZero(m.Ports[i]) { // not required
			continue
		}

		if m.Ports[i] != nil {
			if err := m.Ports[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Ports" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ListContainer) validateSize(formats strfmt.Registry) error {

	if swag.IsZero(m.Size) { // not required
		return nil
	}

	if m.Size != nil {
		if err := m.Size.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Size")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ListContainer) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ListContainer) UnmarshalBinary(b []byte) error {
	var res ListContainer
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
