// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ListRegistriesReport ListRegistriesReport is the report when querying for a sorted list of
// registries which may be contacted during certain operations.
//
// swagger:model ListRegistriesReport
type ListRegistriesReport struct {

	// registries
	Registries []string `json:"Registries"`
}

// Validate validates this list registries report
func (m *ListRegistriesReport) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ListRegistriesReport) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ListRegistriesReport) UnmarshalBinary(b []byte) error {
	var res ListRegistriesReport
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
