// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OCIRuntimeInfo OCIRuntimeInfo describes the runtime (crun or runc) being
// used with podman
//
// swagger:model OCIRuntimeInfo
type OCIRuntimeInfo struct {

	// name
	Name string `json:"name,omitempty"`

	// package
	Package string `json:"package,omitempty"`

	// path
	Path string `json:"path,omitempty"`

	// version
	Version string `json:"version,omitempty"`
}

// Validate validates this o c i runtime info
func (m *OCIRuntimeInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OCIRuntimeInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OCIRuntimeInfo) UnmarshalBinary(b []byte) error {
	var res OCIRuntimeInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
