// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PodCreateConfig pod create config
//
// swagger:model PodCreateConfig
type PodCreateConfig struct {

	// c group parent
	CGroupParent string `json:"cgroup-parent,omitempty"`

	// hostname
	Hostname string `json:"hostname,omitempty"`

	// infra
	Infra bool `json:"infra,omitempty"`

	// infra command
	InfraCommand string `json:"infra-command,omitempty"`

	// infra image
	InfraImage string `json:"infra-image,omitempty"`

	// labels
	Labels []string `json:"labels"`

	// name
	Name string `json:"name,omitempty"`

	// publish
	Publish []string `json:"publish"`

	// share
	Share string `json:"share,omitempty"`
}

// Validate validates this pod create config
func (m *PodCreateConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PodCreateConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PodCreateConfig) UnmarshalBinary(b []byte) error {
	var res PodCreateConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
