// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RemoteSocket RemoteSocket describes information about the API socket
//
// swagger:model RemoteSocket
type RemoteSocket struct {

	// exists
	Exists bool `json:"exists,omitempty"`

	// path
	Path string `json:"path,omitempty"`
}

// Validate validates this remote socket
func (m *RemoteSocket) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RemoteSocket) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RemoteSocket) UnmarshalBinary(b []byte) error {
	var res RemoteSocket
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
