// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// Signal A Signal is a number describing a process signal.
//
// It implements the os.Signal interface.
//
// swagger:model Signal
type Signal int64

// Validate validates this signal
func (m Signal) Validate(formats strfmt.Registry) error {
	return nil
}
