// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// UTSMode UTSMode represents the UTS namespace of the container.
//
// swagger:model UTSMode
type UTSMode string

// Validate validates this u t s mode
func (m UTSMode) Validate(formats strfmt.Registry) error {
	return nil
}
